# Generated by Django 5.2.16 on 2026-07-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SONABEL', 'Electricity'), ('ONEA', 'Water')], max_length=10)),
                ('period', models.DateField()),
                ('deadline', models.DateField()),
                ('price_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('previous_index', models.IntegerField()),
                ('new_index', models.IntegerField()),
                ('total_consumption', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
    ]
