# Generated by Django 5.2.16 on 2026-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('SONABEL', 'SONABEL'), ('ONEA', 'ONEA')], max_length=10),
        ),
    ]
