# Generated by Django 5.2.16 on 2026-08-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_organisation_membership_bill_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
