# Generated by Django 5.2.16 on 2026-08-03 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_organization_membership_bill_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
