# Generated by Django 5.2.16 on 2026-08-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_organization_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('member', 'member')], default='member', max_length=10),
        ),
    ]
